[tool.poetry]
name = "chainlink-anchorpy"
version = "0.1.0"
description = "The Python Anchor client."
readme = "README.md"
repository = "https://github.com/kevinheavey/anchorpy"
documentation = "https://kevinheavey.github.io/anchorpy/"
authors = ["kevinheavey <kevinheavey123@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
construct-typing = "^0.5.1"
solana = "^0.21.0"
sumtypes = "^0.1a6"
apischema = "^0.16.6"
borsh-construct = "^0.1.0"
websockets = "^10.0"
toolz = "^0.11.2"
jsonrpcclient = "^4.0.1"
zstandard = "^0.17.0"
pytest = "^6.2.5"
pytest-xprocess = "^0.18.1"
pytest-asyncio = "^0.17.2"
more-itertools = "^8.11.0"
typer = { version = "^0.4.0", optional = true }
ipython = { version = "^8.0.1", optional = true }
pyheck = "^0.1.4"

[tool.poetry.extras]
cli = ["typer", "ipython"]


[tool.poetry.scripts]
chainlink_anchorpy = "chainlink_anchorpy.cli:app"

[tool.poetry.dev-dependencies]
wemake-python-styleguide = "^0.15.3"
mypy = "^0.910"
black = "^21.7b0"
pydocstyle = "^6.1.1"
isort = "^5.9.3"
mkdocs-material = "^8.1.7"
bump2version = "^1.0.1"
pyserum = "^0.5.0-alpha.0"
mkdocstrings = "^0.17.0"
bandit = "1.7.2"

[tool.poetry.plugins.pytest11]
pytest_chainlink_anchorpy = "chainlink_anchorpy.pytest_plugin"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
